<?xml version="1.0" encoding="utf-8"?><Database Name="AAC" Class="SportclubManagerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=COM25\SQLEXPRESS;Initial Catalog=AAC;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AACConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbDocument" Member="Documents">
    <Type Name="Document">
      <Column Name="DocumentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DocumentName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DocumentLocation" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Document" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbRole" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Role_User" Member="Users" ThisKey="RoleID" OtherKey="RoleID" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.tbMemberEvidence" Member="MemberEvidences">
    <Type Name="MemberEvidence">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MemberID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Present" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Group_MemberEvidence" Member="Group" ThisKey="GroupID" OtherKey="GroupID" Type="Group" IsForeignKey="true" />
      <Association Name="tbMember_MemberEvidence" Member="Member" ThisKey="MemberID" OtherKey="MemberID" Type="Member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbGroup" Member="Groups">
    <Type Name="Group">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CoachID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Group_MemberEvidence" Member="MemberEvidences" ThisKey="GroupID" OtherKey="GroupID" Type="MemberEvidence" />
      <Association Name="Group_tbMember" Member="Members" ThisKey="GroupID" OtherKey="GroupID" Type="Member" />
      <Association Name="User_Group" Member="User" ThisKey="CoachID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbUser" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserLogin" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserPassword" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_Document" Member="Documents" ThisKey="UserID" OtherKey="UserID" Type="Document" />
      <Association Name="User_Group" Member="Groups" ThisKey="UserID" OtherKey="CoachID" Type="Group" />
      <Association Name="Role_User" Member="Role" ThisKey="RoleID" OtherKey="RoleID" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbMember" Member="Members">
    <Type Name="Member">
      <Column Name="MemberID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mother" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Father" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FatherMail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MotherMail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="FatherPhoneNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MotherPhoneNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PhotoLocation" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="tbMember_MemberEvidence" Member="MemberEvidences" ThisKey="MemberID" OtherKey="MemberID" Type="MemberEvidence" />
      <Association Name="Group_tbMember" Member="Group" ThisKey="GroupID" OtherKey="GroupID" Type="Group" IsForeignKey="true" />
    </Type>
  </Table>
</Database>